version: '3.8'

services:
  rabbitmq:
    image: 'rabbitmq:3.8-management-alpine'
    container_name: rabbitmq-smartranking
    hostname: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      -  ./rabbitmqdata:/var/lib/rabbitmq/mnesia
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - smartranking

networks:
  smartranking:
    driver: bridge