apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter
  labels:
    run: jupyter
  namespace: jupyter
spec:
  replicas: 1
  selector:
    matchLabels:
      run: jupyter
  template:
    metadata:
      labels:
        run: jupyter
    spec:
      containers:
      - name: jupyter
        image: jupyter/scipy-notebook:abdb27a6dfbb
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
