export const EMAIL_CHANGED = 'EMAIL_CHANGED'
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED'
export const LOGIN_USER = 'LOGIN_USER'


export const EMPLOYEE_UPDATE = 'EMPLOYEE_UPDATE'
export const EMPLOYEE_CREATE = 'EMPLOYEE_CREATE'
export const SELECT_EMPLOYEE = 'SELECT_EMPLOYEE'
export const RESET_EMPLOYEE = 'RESET_EMPLOYEE'
export const FETCH_EMPLOYEES = 'FETCH_EMPLOYEES'
