# FROM redis


# # Bundle APP files
# # COPY src src/
# # COPY package.json .
# # COPY ./redis.conf /usr/local/etc/redis/redis.conf

# # Install app dependencies
# # ENV NPM_CONFIG_LOGLEVEL warn
# # RUN npm install --production

# # Show current folder structure in logs
# # RUN ls -al -R

# CMD [ "redis-server"]