POST http://localhost:3000/reports
Content-Type: application/json

{
  "price": 25000,
  "make": "Vw",
  "year": 2015,
  "model": "up!",
  "mileage": 35000,
  "lng": 12.1255456,
  "lat": 12.6654552
}

### Approve Report

PATCH  http://localhost:3000/reports/1
Content-Type: application/json

{
  "approved": true
}

### get estimates

GET  http://localhost:3000/reports?make=ford&model=up!&year=2015&lng=0&lat=0&mileage=2000
Content-Type: application/json