version: '3'

services:
  redis-server:
    image: 'redis'
  node-app:
    #restart: always
    restart: on-failure
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - "redis-server"

