apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database
spec:
  resources:
    requests:
      storage: 1Gi
  # volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce

# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: database
# spec:
#   resources:
#     requests:
#       storage: 1Gi
#   # volumeMode: Filesystem
#   accessModes:
#     - ReadWriteOnce
#   # selector:
#   #   matchLabels:
#   #     volume: my-volume
