apiVersion: v1
kind: Pod
metadata:
  name: kuard-tls
spec:
  containers:
    - name: kuard-tls
      image: gcr.io/kuar-demo/kuard-amd64:blue
      imagePullPolicy: Always
      resources:
        limits:
          memory: 200Mi
          cpu: 100m
      volumeMounts:
        - mountPath: /tls
          name: tls-certs
          readOnly: true
  volumes:
    - name: tls-certs
      secret:
        secretName: kuard-tls