<?php
$teste = "ALO MUNDO";
echo "\n\n  COM ASPAS DUPLAS O PHP PROCURARA POR CARACTERES DE FORMATAÇÂO E VERIAVEIS DENTRO DA STRING PARA PROCESSALAS POR EXEMPO : $teste";
echo "\n\n";
echo '\n\nCOM ASPAS SIMPLES O PHP PROCESSARA A STRING DA FORMA COM QUE ELA FOI ESCRITA POR EXEMPLO : $teste';
echo "\n\n";