### create new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "balbimarcus3@gmail.com",
  "password": "abc123"
}

### signin a user
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "balbimarcus2@gmail.com",
  "password": "abc123"
}

### who am I
GET http://localhost:3000/auth/whoami
Content-Type: application/json

### sign out
POST http://localhost:3000/auth/signout
Content-Type: application/json



### find user
GET http://localhost:3000/auth/1
Content-Type: application/json


### find all users
GET http://localhost:3000/auth/?email=blalba@blalba.com
Content-Type: application/json


### Remove a user
DELETE  http://localhost:3000/auth/5
Content-Type: application/json


### Remove a user
PATCH   http://localhost:3000/auth/1
Content-Type: application/json

{
  "password": "sssdas2"
}